name: Build and Push to registry

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags:
            - ghcr.io/calendar-team/sqlite-to-r2:${{ github.sha }}
            - ghcr.io/calendar-team/sqlite-to-r2:latest

